/* Build script for the Vault Gateway daemon.

   Separate from the repo's esbuild.config.mjs on purpose: that file is owned
   by the plugin/app builds (and by another agent), and this bundle has
   opposite requirements — CJS for node, node builtins external, no DOM.

   Output is a single self-contained daemons/gateway/dist/gateway.js so the
   launchd plist can point at one absolute path with no node_modules
   resolution at runtime. Node builtins are the only externals; everything the
   daemon imports out of src/ is inlined.

   A second entry bundles the read-only `apple-health` CLI
   (src/apple-health/cli.ts) to dist/apple-health.js with a node shebang, for
   the ~/.local/bin/apple-health symlink. A third bundles the Apple Health
   heavy-read worker to dist/apple-health-worker.js, which the daemon loads
   from its own directory (src/apple-health/offload.ts).

   Usage: node daemons/gateway/build.mjs [--watch] [--production] */

import { build, context } from "esbuild";
import { chmodSync } from "node:fs";
import builtins from "builtin-modules";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes("--watch");
const production = process.argv.includes("--production");

/** @type {import("esbuild").BuildOptions} */
const options = {
  entryPoints: [resolve(here, "src/main.ts")],
  outfile: resolve(here, "dist/gateway.js"),
  bundle: true,
  platform: "node",
  target: "node24",
  format: "cjs",
  /* Node builtins only. `obsidian` is listed because the shared platform
     module's type-only import of it is erased, but a mid-refactor value
     import would otherwise fail the build with a confusing resolve error
     rather than a clear runtime one. */
  /* node:sqlite is newer than the builtin-modules list, so it is named
     explicitly (the Apple Health store loads it lazily). */
  external: [...builtins, ...builtins.map(b => `node:${b}`), "node:sqlite", "obsidian", "electron"],
  sourcemap: production ? false : "inline",
  minify: production,
  logLevel: "info",
  /* The daemon never runs in a browser; make that explicit so any accidental
     DOM-touching import fails loudly at build time instead of at 3am. */
  define: { "process.env.VAULT_GATEWAY_BUILD": JSON.stringify(production ? "production" : "development") },
  banner: {
    js: "/* Vault Gateway daemon — generated by daemons/gateway/build.mjs. Do not edit. */",
  },
};

/** @type {import("esbuild").BuildOptions} */
const cliOptions = {
  ...options,
  entryPoints: [resolve(here, "src/apple-health/cli.ts")],
  outfile: resolve(here, "dist/apple-health.js"),
  /* The shebang must be the first line; the symlink in ~/.local/bin is run
     directly. node:sqlite's ExperimentalWarning is filtered in code
     (src/apple-health/sqlite.ts), so no --no-warnings flag is needed. */
  banner: {
    js: "#!/usr/bin/env node\n/* apple-health CLI — generated by daemons/gateway/build.mjs. Do not edit. */",
  },
};

/* The Apple Health heavy-read worker (src/apple-health/offload.ts). It must
   sit next to dist/gateway.js: the daemon resolves it from its own
   __dirname. */
/** @type {import("esbuild").BuildOptions} */
const workerOptions = {
  ...options,
  entryPoints: [resolve(here, "src/apple-health/worker.ts")],
  outfile: resolve(here, "dist/apple-health-worker.js"),
  banner: {
    js: "/* Vault Gateway apple-health worker — generated by daemons/gateway/build.mjs. Do not edit. */",
  },
};

const makeExecutable = () => chmodSync(cliOptions.outfile, 0o755);

if (watch) {
  const ctx = await context(options);
  const cliCtx = await context({
    ...cliOptions,
    plugins: [{ name: "chmod", setup(b) { b.onEnd(r => { if (r.errors.length === 0) makeExecutable(); }); } }],
  });
  const workerCtx = await context(workerOptions);
  await Promise.all([ctx.watch(), cliCtx.watch(), workerCtx.watch()]);
  console.log("[gateway] watching…");
} else {
  await Promise.all([build(options), build(cliOptions), build(workerOptions)]);
  makeExecutable();
  console.log(`[gateway] built ${options.outfile}`);
  console.log(`[gateway] built ${cliOptions.outfile}`);
  console.log(`[gateway] built ${workerOptions.outfile}`);
}
