/* Build script for the Vault Gateway daemon.

   Separate from the repo's esbuild.config.mjs on purpose: that file is owned
   by the plugin/app builds (and by another agent), and this bundle has
   opposite requirements — CJS for node, node builtins external, no DOM.

   Output is a single self-contained daemons/gateway/dist/gateway.js so the
   launchd plist can point at one absolute path with no node_modules
   resolution at runtime. Node builtins are the only externals; everything the
   daemon imports out of src/ is inlined.

   Usage: node daemons/gateway/build.mjs [--watch] [--production] */

import { build, context } from "esbuild";
import builtins from "builtin-modules";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes("--watch");
const production = process.argv.includes("--production");

/** @type {import("esbuild").BuildOptions} */
const options = {
  entryPoints: [resolve(here, "src/main.ts")],
  outfile: resolve(here, "dist/gateway.js"),
  bundle: true,
  platform: "node",
  target: "node24",
  format: "cjs",
  /* Node builtins only. `obsidian` is listed because the shared platform
     module's type-only import of it is erased, but a mid-refactor value
     import would otherwise fail the build with a confusing resolve error
     rather than a clear runtime one. */
  external: [...builtins, ...builtins.map(b => `node:${b}`), "obsidian", "electron"],
  sourcemap: production ? false : "inline",
  minify: production,
  logLevel: "info",
  /* The daemon never runs in a browser; make that explicit so any accidental
     DOM-touching import fails loudly at build time instead of at 3am. */
  define: { "process.env.VAULT_GATEWAY_BUILD": JSON.stringify(production ? "production" : "development") },
  banner: {
    js: "/* Vault Gateway daemon — generated by daemons/gateway/build.mjs. Do not edit. */",
  },
};

if (watch) {
  const ctx = await context(options);
  await ctx.watch();
  console.log("[gateway] watching…");
} else {
  await build(options);
  console.log(`[gateway] built ${options.outfile}`);
}
